# Generated by Django 2.2.6 on 2019-10-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0002_album_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='imange',
            new_name='image',
        ),
    ]
